// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChL0LFnQEdb7rE2rvgLH5N0YHduGaeHU4',
    appId: '1:69463701496:web:6e1488734baab9eb39480d',
    messagingSenderId: '69463701496',
    projectId: 'authentication-ec024',
    authDomain: 'authentication-ec024.firebaseapp.com',
    storageBucket: 'authentication-ec024.appspot.com',
    measurementId: 'G-L7G2P3ZCH8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZi7rCHGdCW4nUHaA_dsv9uF9uyO67kyU',
    appId: '1:69463701496:android:873d638336900e4039480d',
    messagingSenderId: '69463701496',
    projectId: 'authentication-ec024',
    storageBucket: 'authentication-ec024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDodUV_CiBaIJCwdGjf0vSxblkhtpOXqqc',
    appId: '1:69463701496:ios:3d19a924d6ed196a39480d',
    messagingSenderId: '69463701496',
    projectId: 'authentication-ec024',
    storageBucket: 'authentication-ec024.appspot.com',
    androidClientId: '69463701496-co1c3tioeqc339l24srtvokd6m3k3rfl.apps.googleusercontent.com',
    iosClientId: '69463701496-l9aal7hau3ouofd61flpkprgjfl91agc.apps.googleusercontent.com',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDodUV_CiBaIJCwdGjf0vSxblkhtpOXqqc',
    appId: '1:69463701496:ios:3d19a924d6ed196a39480d',
    messagingSenderId: '69463701496',
    projectId: 'authentication-ec024',
    storageBucket: 'authentication-ec024.appspot.com',
    androidClientId: '69463701496-co1c3tioeqc339l24srtvokd6m3k3rfl.apps.googleusercontent.com',
    iosClientId: '69463701496-l9aal7hau3ouofd61flpkprgjfl91agc.apps.googleusercontent.com',
    iosBundleId: 'com.example.authentication',
  );
}
